# Generated by Django 2.1.5 on 2020-06-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200614_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='homedepot_url',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_chart',
            field=models.CharField(max_length=120),
        ),
    ]
