# Generated by Django 2.1.5 on 2020-07-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200618_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
